### ISSUE TITLE
Transaction is failing always.

### ISSUE THREAD

**Issue by DedicatedDev** [oasisprotocol/emerald-paratime#17]
I'm trying to make demo web app right now. 
my smart contract was passed by test in hardhat. 
Also I've succeed in deploy. 
but when I try to call method of my smart contract, transaction is failing. 
I've posted detailed screenshot on the slack tech support channel. 
My contract was deployed to test net. 
Any idea?
Best.

**Comment by matevz** [comment]
Resolved offline on slack.
